### ISSUE TITLE
한글 입력 모드에서 escape 시에 자동 영문 전환

### ISSUE THREAD

**Issue by Joungkyun** [Joungkyun/iputty#12]
한텀에서 처럼, 한글 입력 모드에서 escape를 눌렸을 경우 자동으로 영문으로 전환되는 기능

http://vany.tistory.com/entry/PuTTY-Esc로-영문-전환하기 패치 참조

**Comment by qqkookie** [comment]
.이 기능을 매우 유용하게 쓰고 있습니다. 그런데 ESCape 뿐만 아니라 Return 리턴 키 일 때도 영문모드로 전환 되도록 하면 좋겠습니다.  적어도 그런 옵션이 있었으면 합니다.
